#!/usr/bin/env python3
"""Generate independent, exhaustive-tail and boundary oracles for production validation."""
import argparse
import base64
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location('fixtures', ROOT / 'scripts/generate-fixtures.py')
legacy = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(legacy)


def deserialize_bytes(values, offset=0):
    """Independently validate fixture lengths, leading zeroes and canonical ABI words."""
    count = values[offset]
    words = values[offset + 1:offset + 1 + count]
    pending, length = values[offset + 1 + count:offset + 3 + count]
    if count < 0 or len(words) != count or not 0 <= length < 31:
        raise ValueError('invalid ByteArray shape')
    if any(not 0 <= word < 2**248 for word in words) or not 0 <= pending < 2**(8 * length):
        raise ValueError('invalid ByteArray word')
    decoded = b''.join(word.to_bytes(31, 'big') for word in words)
    return decoded + pending.to_bytes(length, 'big'), offset + count + 3


def checked_fixture(data):
    expected = base64.b64encode(data)
    assert base64.b64decode(expected, validate=True) == data
    values = legacy.fixture(data)
    decoded_input, offset = deserialize_bytes(values)
    decoded_output, offset = deserialize_bytes(values, offset)
    assert decoded_input == data and decoded_output == expected and offset == len(values)
    return values


def random_bytes(seed, length):
    blocks = (hashlib.sha256(f'base64-accuracy-v1:{seed}:{length}:{index}'.encode()).digest()
        for index in range((length + 31) // 32))
    return b''.join(blocks)[:length]


def families():
    yield 'pairs', [value.to_bytes(2, 'big') for value in range(65536)], 1024, 100000
    sextets = []
    for background in [0, 21, 42, 63]:
        for position in range(4):
            for value in range(64):
                digits = [background] * 4
                digits[position] = value
                word = sum(digit << (18 - 6 * index) for index, digit in enumerate(digits))
                sextets.append(word.to_bytes(3, 'big'))
    yield 'sextets', sextets, 256, 100000
    isolated = [bytes([value if index == position else 0 for index in range(3)])
        for position in range(3) for value in range(256)]
    yield 'isolated', isolated, 256, 100000
    sizes = sorted(set(range(195)) | {255, 256, 257, 511, 512, 513, 1023, 1024, 1025,
        4095, 4096, 4097, 8191, 8192, 8193, 16383, 16384, 16385})
    yield 'random', [random_bytes(seed, size) for seed in range(4) for size in sizes], 64, 12000
    sizes = [23, 24, 25, 30, 31, 32, 33, 46, 47, 48, 49, 61, 62, 63, 64,
        92, 93, 94, 95, 96, 124, 125, 126]
    sparse = []
    for size in sizes:
        for offset in range(size):
            for value in [1, 255]:
                data = bytearray(size)
                data[offset] = value
                sparse.append(bytes(data))
    yield 'sparse', sparse, 64, 12000
    svg = '<svg><text>Beast #123 — 🐉</text></svg>'.encode()
    nested = json.dumps({'name': 'Beast #123', 'image':
        'data:image/svg+xml;base64,' + base64.b64encode(svg).decode()},
        ensure_ascii=False, separators=(',', ':')).encode()
    yield 'nested', [svg, nested], 64, 12000


def outputs():
    result, batches, coverage = {}, [], {}
    for family, cases, max_cases, max_bytes in families():
        coverage[family] = len(cases)
        chunks, batch, budget = [], [], 0
        for data in cases:
            if batch and (len(batch) >= max_cases or budget + len(data) > max_bytes):
                chunks.append(batch)
                batch, budget = [], 0
            batch.append(data)
            budget += len(data)
        if batch:
            chunks.append(batch)
        for index, batch in enumerate(chunks):
            name = f'{family}_{index:03d}'
            path = f'fixtures/accuracy/{name}.txt'
            values = [len(batch)]
            for data in batch:
                values.extend(checked_fixture(data))
            result[path] = legacy.render_felts(values)
            batches.append({'name': name, 'fixture': path, 'cases': len(batch)})
    # Send the entire existing oracle corpus through the separately compiled contract too.
    old_manifest = json.loads((ROOT / 'fixtures/manifest.json').read_text())
    coverage['legacy_production'] = old_manifest['oracle_cases']
    for index, batch in enumerate(old_manifest['oracle_batches']):
        batches.append({'name': f'legacy_{index:03d}', **batch})
    tests = ['// Generated by scripts/generate-accuracy-fixtures.py; edit the generator.',
        'use super::accuracy_support::accuracy_batch;']
    for batch in batches:
        tests += ['#[test]', f'fn accuracy_{batch["name"]}() {{',
            f'    accuracy_batch("{batch["fixture"]}", {batch["cases"]});', '}']
    result['tests/accuracy_validation.cairo'] = '\n'.join(tests) + '\n'
    manifest = {'schema': 1, 'oracle': 'Python standard library base64.b64encode',
        'random': 'SHA-256 blocks with four distinct seeds per length', 'coverage': coverage,
        'cases': sum(coverage.values()), 'batches': batches,
        'generated_sha256': {path: hashlib.sha256(content.encode()).hexdigest()
            for path, content in sorted(result.items())}}
    result['fixtures/accuracy-manifest.json'] = json.dumps(manifest, indent=2, sort_keys=True) + '\n'
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify without modifying files')
    args = parser.parse_args()
    result = outputs()
    mismatches = []
    for relative, content in result.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text() != content:
                mismatches.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    extras = {str(path.relative_to(ROOT)) for path in (ROOT / 'fixtures/accuracy').glob('*.txt')} - set(result)
    mismatches.extend(sorted(extras))
    if mismatches:
        parser.exit(1, 'Accuracy fixture drift: ' + ', '.join(mismatches) + '\n')
    manifest = json.loads(result['fixtures/accuracy-manifest.json'])
    print(f'{manifest["cases"]} accuracy cases in {len(manifest["batches"])} batches; '
        + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
