#!/usr/bin/env python3
"""Generate deterministic Python Base64 oracle data, never from the Cairo encoder."""
import argparse
import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIZES = sorted(set(range(13)) | {22, 23, 24, 30, 31, 32, 33, 45, 46, 47, 48,
    61, 62, 63, 64, 91, 92, 93, 94, 95, 96, 127, 128, 129, 255, 256, 257,
    511, 512, 513, 1023, 1024, 1025, 2047, 2048, 2049, 4095, 4096, 4097,
    8191, 8192, 8193, 16383, 16384, 16385})
ORACLE_SIZES = list(range(97)) + [127, 128, 129, 255, 256, 257, 511, 512, 513,
    1023, 1024, 1025, 2048, 4095, 4096, 4097, 8191, 8192, 8193, 16384]
PATTERNS = ['zero', 'ff', 'ascending', 'alternating', 'pseudorandom']


def payload(pattern, size):
    if pattern == 'a5':
        return bytes([0xa5]) * size
    if pattern == 'zero':
        return bytes(size)
    if pattern == 'ff':
        return bytes([255]) * size
    if pattern == 'ascending':
        return bytes(i % 256 for i in range(size))
    if pattern == 'alternating':
        return bytes(0x55 if i % 2 == 0 else 0xaa for i in range(size))
    if pattern == 'text':
        text = b'<svg xmlns="http://www.w3.org/2000/svg"><text>Beast #123</text></svg>\n'
        return (text * ((size + len(text) - 1) // len(text)))[:size]
    if pattern == 'pseudorandom':
        state = 4648 + size
        result = bytearray()
        for _ in range(size):
            state = (state * 1664525 + 1013904223) % 4294967296
            result.append(state // 16777216)
        return bytes(result)
    raise ValueError(pattern)


def serialize_bytes(data):
    """Cairo ByteArray Serde: word count, big-endian bytes31 words, pending word, length."""
    count, remainder = divmod(len(data), 31)
    return [count] + [int.from_bytes(data[i:i + 31], 'big')
        for i in range(0, count * 31, 31)] + [int.from_bytes(data[count * 31:], 'big'), remainder]


def fixture(data):
    return serialize_bytes(data) + serialize_bytes(base64.b64encode(data))


def render_felts(values):
    return ''.join(f'{value}\n' for value in values)


def outputs():
    result = {}
    benchmarks = []
    for pattern, sizes in [('a5', SIZES)] + [(p, [3, 31, 32, 93, 1024, 8192, 8193, 16384])
            for p in PATTERNS + ['text']]:
        for size in sizes:
            case_id = f'{pattern}_{size}'
            data = payload(pattern, size)
            path = f'fixtures/benchmarks/{case_id}.txt'
            result[path] = render_felts(fixture(data))
            benchmarks.append({'case': case_id, 'pattern': pattern, 'input_bytes': size,
                'encoded_bytes': len(base64.b64encode(data)), 'fixture': path,
                'input_sha256': hashlib.sha256(data).hexdigest(),
                'output_sha256': hashlib.sha256(base64.b64encode(data)).hexdigest()})
    cases = [bytes([i]) for i in range(256)]
    cases += [payload(pattern, size) for pattern in PATTERNS for size in ORACLE_SIZES]
    batches, batch, budget = [], [], 0
    for data in cases:
        if batch and (len(batch) == 64 or budget + len(data) > 12000):
            batches.append(batch)
            batch, budget = [], 0
        batch.append(data)
        budget += len(data)
    if batch:
        batches.append(batch)
    oracle = []
    for index, batch in enumerate(batches):
        path = f'fixtures/oracle/batch_{index:02d}.txt'
        values = [len(batch)]
        for data in batch:
            values.extend(fixture(data))
        result[path] = render_felts(values)
        oracle.append({'fixture': path, 'cases': len(batch)})
    benchmark_tests = ['// Generated by scripts/generate-fixtures.py; edit the generator.',
        'use super::benchmark_support::benchmark_case;']
    for case in benchmarks:
        benchmark_tests += ['#[test]', f'fn bench_{case["case"]}() {{',
            f'    benchmark_case("{case["fixture"]}", {case["input_bytes"]});', '}']
    result['tests/lab_benchmarks.cairo'] = '\n'.join(benchmark_tests) + '\n'
    oracle_tests = ['// Generated by scripts/generate-fixtures.py; edit the generator.',
        'use super::benchmark_support::oracle_batch;']
    for index, batch in enumerate(oracle):
        oracle_tests += ['#[test]', f'fn oracle_batch_{index:02d}() {{',
            f'    oracle_batch("{batch["fixture"]}", {batch["cases"]});', '}']
    result['tests/oracle_correctness.cairo'] = '\n'.join(oracle_tests) + '\n'
    manifest = {'schema': 1, 'oracle': 'Python standard library base64.b64encode',
        'byte_array_encoding': 'Cairo Serde; big-endian 31-byte words; pending word may be zero',
        'pseudorandom': 'u32 LCG seed=4648+size, a=1664525, c=1013904223, emit high byte',
        'text': 'Repeated and truncated synthetic SVG ASCII; not a measured Beast workload',
        'repetitions': 3, 'benchmarks': benchmarks,
        'oracle_cases': len(cases), 'oracle_batches': oracle,
        'generated_sha256': {path: hashlib.sha256(content.encode()).hexdigest()
            for path, content in sorted(result.items())}}
    result['fixtures/manifest.json'] = json.dumps(manifest, indent=2, sort_keys=True) + '\n'
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if generated files differ; never write')
    args = parser.parse_args()
    mismatches = []
    result = outputs()
    for relative, content in result.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text() != content:
                mismatches.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    extras = {str(path.relative_to(ROOT)) for folder in ['fixtures/benchmarks', 'fixtures/oracle']
        for path in (ROOT / folder).glob('*.txt')} - set(result)
    mismatches.extend(sorted(extras))
    if mismatches:
        parser.exit(1, 'Fixture drift: ' + ', '.join(mismatches) + '\n')
    manifest = json.loads(result['fixtures/manifest.json'])
    print(f'{len(manifest["benchmarks"])} benchmark cases; {manifest["oracle_cases"]} oracle cases; generated files verified' if args.check
        else f'Generated {len(manifest["benchmarks"])} benchmark cases and {manifest["oracle_cases"]} oracle cases')


if __name__ == '__main__':
    main()
