[package]
name = "game_components_metagame"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_introspection.workspace = true
game_components_interfaces = { path = "../interfaces" }
game_components_utilities = { path = "../utilities" }
interfaces = { git = "https://github.com/Provable-Games/metagame_extensions.git", branch = "next" }

[dev-dependencies]
snforge_std.workspace = true
openzeppelin_interfaces.workspace = true
game_components_testing = { path = "../testing" }
game_components_test_common = { path = "../test_common" }

[[target.starknet-contract]]
