[package]
name = "game_components_metagame"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true
game_components_interfaces = { path = "../interfaces" }
game_components_minigame = { path = "../minigame" }
game_components_registry = { path = "../registry" }
game_components_token = { path = "../token" }
game_components_utils = { path = "../utils" }
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true

[dev-dependencies]
snforge_std.workspace = true
game_components_testing = { path = "../testing" }
game_components_test_common = { path = "../test_common" }

[[target.starknet-contract]]
sierra = true
casm = true