[package]
name = "game_components_metagame"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
game_components_token = { path = "../token" }
openzeppelin_introspection = "1.0.0"
openzeppelin_token = "1.0.0"
openzeppelin_access = "1.0.0"

[dev-dependencies]
snforge_std = "0.45.0"
game_components_minigame = { path = "../minigame" }

[[target.starknet-contract]]
sierra = true
casm = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"
