[package]
name = "game_components_token_optimized"
version = "1.0.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"

# Game components dependencies
game_components_minigame = { path = "../minigame" }
game_components_metagame = { path = "../metagame" }
game_components_utils = { path = "../utils" }

[[target.starknet-contract]]
sierra = true 