[package]
name = "game_components_tokenomics"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true
ekubo.workspace = true
game_components_interfaces = { path = "../interfaces" }

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true

[lib]
