[package]
name = "game_components_interfaces"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
ekubo.workspace = true
interfaces = { git = "https://github.com/Provable-Games/metagame_extensions.git", branch = "next" }

[lib]
