[package]
name = "game_components_economy"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true
ekubo.workspace = true
game_components_interfaces = { path = "../interfaces" }

[dev-dependencies]
snforge_std.workspace = true
game_components_testing = { path = "../testing" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true

[lib]

[tool.snforge]
fuzzer_runs = 24

[[tool.snforge.fork]]
name = "MAINNET"
url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_10"
block_id.number = "1100000"

[[tool.snforge.fork]]
name = "SEPOLIA"
url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_10"
block_id.number = "14328816"
