// Generated by scripts/generate-accuracy-fixtures.py; edit the generator.
use super::accuracy_support::accuracy_batch;
#[test]
fn accuracy_pairs_000() {
    accuracy_batch("fixtures/accuracy/pairs_000.txt", 1024);
}
#[test]
fn accuracy_pairs_001() {
    accuracy_batch("fixtures/accuracy/pairs_001.txt", 1024);
}
#[test]
fn accuracy_pairs_002() {
    accuracy_batch("fixtures/accuracy/pairs_002.txt", 1024);
}
#[test]
fn accuracy_pairs_003() {
    accuracy_batch("fixtures/accuracy/pairs_003.txt", 1024);
}
#[test]
fn accuracy_pairs_004() {
    accuracy_batch("fixtures/accuracy/pairs_004.txt", 1024);
}
#[test]
fn accuracy_pairs_005() {
    accuracy_batch("fixtures/accuracy/pairs_005.txt", 1024);
}
#[test]
fn accuracy_pairs_006() {
    accuracy_batch("fixtures/accuracy/pairs_006.txt", 1024);
}
#[test]
fn accuracy_pairs_007() {
    accuracy_batch("fixtures/accuracy/pairs_007.txt", 1024);
}
#[test]
fn accuracy_pairs_008() {
    accuracy_batch("fixtures/accuracy/pairs_008.txt", 1024);
}
#[test]
fn accuracy_pairs_009() {
    accuracy_batch("fixtures/accuracy/pairs_009.txt", 1024);
}
#[test]
fn accuracy_pairs_010() {
    accuracy_batch("fixtures/accuracy/pairs_010.txt", 1024);
}
#[test]
fn accuracy_pairs_011() {
    accuracy_batch("fixtures/accuracy/pairs_011.txt", 1024);
}
#[test]
fn accuracy_pairs_012() {
    accuracy_batch("fixtures/accuracy/pairs_012.txt", 1024);
}
#[test]
fn accuracy_pairs_013() {
    accuracy_batch("fixtures/accuracy/pairs_013.txt", 1024);
}
#[test]
fn accuracy_pairs_014() {
    accuracy_batch("fixtures/accuracy/pairs_014.txt", 1024);
}
#[test]
fn accuracy_pairs_015() {
    accuracy_batch("fixtures/accuracy/pairs_015.txt", 1024);
}
#[test]
fn accuracy_pairs_016() {
    accuracy_batch("fixtures/accuracy/pairs_016.txt", 1024);
}
#[test]
fn accuracy_pairs_017() {
    accuracy_batch("fixtures/accuracy/pairs_017.txt", 1024);
}
#[test]
fn accuracy_pairs_018() {
    accuracy_batch("fixtures/accuracy/pairs_018.txt", 1024);
}
#[test]
fn accuracy_pairs_019() {
    accuracy_batch("fixtures/accuracy/pairs_019.txt", 1024);
}
#[test]
fn accuracy_pairs_020() {
    accuracy_batch("fixtures/accuracy/pairs_020.txt", 1024);
}
#[test]
fn accuracy_pairs_021() {
    accuracy_batch("fixtures/accuracy/pairs_021.txt", 1024);
}
#[test]
fn accuracy_pairs_022() {
    accuracy_batch("fixtures/accuracy/pairs_022.txt", 1024);
}
#[test]
fn accuracy_pairs_023() {
    accuracy_batch("fixtures/accuracy/pairs_023.txt", 1024);
}
#[test]
fn accuracy_pairs_024() {
    accuracy_batch("fixtures/accuracy/pairs_024.txt", 1024);
}
#[test]
fn accuracy_pairs_025() {
    accuracy_batch("fixtures/accuracy/pairs_025.txt", 1024);
}
#[test]
fn accuracy_pairs_026() {
    accuracy_batch("fixtures/accuracy/pairs_026.txt", 1024);
}
#[test]
fn accuracy_pairs_027() {
    accuracy_batch("fixtures/accuracy/pairs_027.txt", 1024);
}
#[test]
fn accuracy_pairs_028() {
    accuracy_batch("fixtures/accuracy/pairs_028.txt", 1024);
}
#[test]
fn accuracy_pairs_029() {
    accuracy_batch("fixtures/accuracy/pairs_029.txt", 1024);
}
#[test]
fn accuracy_pairs_030() {
    accuracy_batch("fixtures/accuracy/pairs_030.txt", 1024);
}
#[test]
fn accuracy_pairs_031() {
    accuracy_batch("fixtures/accuracy/pairs_031.txt", 1024);
}
#[test]
fn accuracy_pairs_032() {
    accuracy_batch("fixtures/accuracy/pairs_032.txt", 1024);
}
#[test]
fn accuracy_pairs_033() {
    accuracy_batch("fixtures/accuracy/pairs_033.txt", 1024);
}
#[test]
fn accuracy_pairs_034() {
    accuracy_batch("fixtures/accuracy/pairs_034.txt", 1024);
}
#[test]
fn accuracy_pairs_035() {
    accuracy_batch("fixtures/accuracy/pairs_035.txt", 1024);
}
#[test]
fn accuracy_pairs_036() {
    accuracy_batch("fixtures/accuracy/pairs_036.txt", 1024);
}
#[test]
fn accuracy_pairs_037() {
    accuracy_batch("fixtures/accuracy/pairs_037.txt", 1024);
}
#[test]
fn accuracy_pairs_038() {
    accuracy_batch("fixtures/accuracy/pairs_038.txt", 1024);
}
#[test]
fn accuracy_pairs_039() {
    accuracy_batch("fixtures/accuracy/pairs_039.txt", 1024);
}
#[test]
fn accuracy_pairs_040() {
    accuracy_batch("fixtures/accuracy/pairs_040.txt", 1024);
}
#[test]
fn accuracy_pairs_041() {
    accuracy_batch("fixtures/accuracy/pairs_041.txt", 1024);
}
#[test]
fn accuracy_pairs_042() {
    accuracy_batch("fixtures/accuracy/pairs_042.txt", 1024);
}
#[test]
fn accuracy_pairs_043() {
    accuracy_batch("fixtures/accuracy/pairs_043.txt", 1024);
}
#[test]
fn accuracy_pairs_044() {
    accuracy_batch("fixtures/accuracy/pairs_044.txt", 1024);
}
#[test]
fn accuracy_pairs_045() {
    accuracy_batch("fixtures/accuracy/pairs_045.txt", 1024);
}
#[test]
fn accuracy_pairs_046() {
    accuracy_batch("fixtures/accuracy/pairs_046.txt", 1024);
}
#[test]
fn accuracy_pairs_047() {
    accuracy_batch("fixtures/accuracy/pairs_047.txt", 1024);
}
#[test]
fn accuracy_pairs_048() {
    accuracy_batch("fixtures/accuracy/pairs_048.txt", 1024);
}
#[test]
fn accuracy_pairs_049() {
    accuracy_batch("fixtures/accuracy/pairs_049.txt", 1024);
}
#[test]
fn accuracy_pairs_050() {
    accuracy_batch("fixtures/accuracy/pairs_050.txt", 1024);
}
#[test]
fn accuracy_pairs_051() {
    accuracy_batch("fixtures/accuracy/pairs_051.txt", 1024);
}
#[test]
fn accuracy_pairs_052() {
    accuracy_batch("fixtures/accuracy/pairs_052.txt", 1024);
}
#[test]
fn accuracy_pairs_053() {
    accuracy_batch("fixtures/accuracy/pairs_053.txt", 1024);
}
#[test]
fn accuracy_pairs_054() {
    accuracy_batch("fixtures/accuracy/pairs_054.txt", 1024);
}
#[test]
fn accuracy_pairs_055() {
    accuracy_batch("fixtures/accuracy/pairs_055.txt", 1024);
}
#[test]
fn accuracy_pairs_056() {
    accuracy_batch("fixtures/accuracy/pairs_056.txt", 1024);
}
#[test]
fn accuracy_pairs_057() {
    accuracy_batch("fixtures/accuracy/pairs_057.txt", 1024);
}
#[test]
fn accuracy_pairs_058() {
    accuracy_batch("fixtures/accuracy/pairs_058.txt", 1024);
}
#[test]
fn accuracy_pairs_059() {
    accuracy_batch("fixtures/accuracy/pairs_059.txt", 1024);
}
#[test]
fn accuracy_pairs_060() {
    accuracy_batch("fixtures/accuracy/pairs_060.txt", 1024);
}
#[test]
fn accuracy_pairs_061() {
    accuracy_batch("fixtures/accuracy/pairs_061.txt", 1024);
}
#[test]
fn accuracy_pairs_062() {
    accuracy_batch("fixtures/accuracy/pairs_062.txt", 1024);
}
#[test]
fn accuracy_pairs_063() {
    accuracy_batch("fixtures/accuracy/pairs_063.txt", 1024);
}
#[test]
fn accuracy_sextets_000() {
    accuracy_batch("fixtures/accuracy/sextets_000.txt", 256);
}
#[test]
fn accuracy_sextets_001() {
    accuracy_batch("fixtures/accuracy/sextets_001.txt", 256);
}
#[test]
fn accuracy_sextets_002() {
    accuracy_batch("fixtures/accuracy/sextets_002.txt", 256);
}
#[test]
fn accuracy_sextets_003() {
    accuracy_batch("fixtures/accuracy/sextets_003.txt", 256);
}
#[test]
fn accuracy_isolated_000() {
    accuracy_batch("fixtures/accuracy/isolated_000.txt", 256);
}
#[test]
fn accuracy_isolated_001() {
    accuracy_batch("fixtures/accuracy/isolated_001.txt", 256);
}
#[test]
fn accuracy_isolated_002() {
    accuracy_batch("fixtures/accuracy/isolated_002.txt", 256);
}
#[test]
fn accuracy_random_000() {
    accuracy_batch("fixtures/accuracy/random_000.txt", 64);
}
#[test]
fn accuracy_random_001() {
    accuracy_batch("fixtures/accuracy/random_001.txt", 64);
}
#[test]
fn accuracy_random_002() {
    accuracy_batch("fixtures/accuracy/random_002.txt", 64);
}
#[test]
fn accuracy_random_003() {
    accuracy_batch("fixtures/accuracy/random_003.txt", 13);
}
#[test]
fn accuracy_random_004() {
    accuracy_batch("fixtures/accuracy/random_004.txt", 2);
}
#[test]
fn accuracy_random_005() {
    accuracy_batch("fixtures/accuracy/random_005.txt", 1);
}
#[test]
fn accuracy_random_006() {
    accuracy_batch("fixtures/accuracy/random_006.txt", 1);
}
#[test]
fn accuracy_random_007() {
    accuracy_batch("fixtures/accuracy/random_007.txt", 1);
}
#[test]
fn accuracy_random_008() {
    accuracy_batch("fixtures/accuracy/random_008.txt", 1);
}
#[test]
fn accuracy_random_009() {
    accuracy_batch("fixtures/accuracy/random_009.txt", 1);
}
#[test]
fn accuracy_random_010() {
    accuracy_batch("fixtures/accuracy/random_010.txt", 1);
}
#[test]
fn accuracy_random_011() {
    accuracy_batch("fixtures/accuracy/random_011.txt", 64);
}
#[test]
fn accuracy_random_012() {
    accuracy_batch("fixtures/accuracy/random_012.txt", 64);
}
#[test]
fn accuracy_random_013() {
    accuracy_batch("fixtures/accuracy/random_013.txt", 64);
}
#[test]
fn accuracy_random_014() {
    accuracy_batch("fixtures/accuracy/random_014.txt", 13);
}
#[test]
fn accuracy_random_015() {
    accuracy_batch("fixtures/accuracy/random_015.txt", 2);
}
#[test]
fn accuracy_random_016() {
    accuracy_batch("fixtures/accuracy/random_016.txt", 1);
}
#[test]
fn accuracy_random_017() {
    accuracy_batch("fixtures/accuracy/random_017.txt", 1);
}
#[test]
fn accuracy_random_018() {
    accuracy_batch("fixtures/accuracy/random_018.txt", 1);
}
#[test]
fn accuracy_random_019() {
    accuracy_batch("fixtures/accuracy/random_019.txt", 1);
}
#[test]
fn accuracy_random_020() {
    accuracy_batch("fixtures/accuracy/random_020.txt", 1);
}
#[test]
fn accuracy_random_021() {
    accuracy_batch("fixtures/accuracy/random_021.txt", 1);
}
#[test]
fn accuracy_random_022() {
    accuracy_batch("fixtures/accuracy/random_022.txt", 64);
}
#[test]
fn accuracy_random_023() {
    accuracy_batch("fixtures/accuracy/random_023.txt", 64);
}
#[test]
fn accuracy_random_024() {
    accuracy_batch("fixtures/accuracy/random_024.txt", 64);
}
#[test]
fn accuracy_random_025() {
    accuracy_batch("fixtures/accuracy/random_025.txt", 13);
}
#[test]
fn accuracy_random_026() {
    accuracy_batch("fixtures/accuracy/random_026.txt", 2);
}
#[test]
fn accuracy_random_027() {
    accuracy_batch("fixtures/accuracy/random_027.txt", 1);
}
#[test]
fn accuracy_random_028() {
    accuracy_batch("fixtures/accuracy/random_028.txt", 1);
}
#[test]
fn accuracy_random_029() {
    accuracy_batch("fixtures/accuracy/random_029.txt", 1);
}
#[test]
fn accuracy_random_030() {
    accuracy_batch("fixtures/accuracy/random_030.txt", 1);
}
#[test]
fn accuracy_random_031() {
    accuracy_batch("fixtures/accuracy/random_031.txt", 1);
}
#[test]
fn accuracy_random_032() {
    accuracy_batch("fixtures/accuracy/random_032.txt", 1);
}
#[test]
fn accuracy_random_033() {
    accuracy_batch("fixtures/accuracy/random_033.txt", 64);
}
#[test]
fn accuracy_random_034() {
    accuracy_batch("fixtures/accuracy/random_034.txt", 64);
}
#[test]
fn accuracy_random_035() {
    accuracy_batch("fixtures/accuracy/random_035.txt", 64);
}
#[test]
fn accuracy_random_036() {
    accuracy_batch("fixtures/accuracy/random_036.txt", 13);
}
#[test]
fn accuracy_random_037() {
    accuracy_batch("fixtures/accuracy/random_037.txt", 2);
}
#[test]
fn accuracy_random_038() {
    accuracy_batch("fixtures/accuracy/random_038.txt", 1);
}
#[test]
fn accuracy_random_039() {
    accuracy_batch("fixtures/accuracy/random_039.txt", 1);
}
#[test]
fn accuracy_random_040() {
    accuracy_batch("fixtures/accuracy/random_040.txt", 1);
}
#[test]
fn accuracy_random_041() {
    accuracy_batch("fixtures/accuracy/random_041.txt", 1);
}
#[test]
fn accuracy_random_042() {
    accuracy_batch("fixtures/accuracy/random_042.txt", 1);
}
#[test]
fn accuracy_random_043() {
    accuracy_batch("fixtures/accuracy/random_043.txt", 1);
}
#[test]
fn accuracy_sparse_000() {
    accuracy_batch("fixtures/accuracy/sparse_000.txt", 64);
}
#[test]
fn accuracy_sparse_001() {
    accuracy_batch("fixtures/accuracy/sparse_001.txt", 64);
}
#[test]
fn accuracy_sparse_002() {
    accuracy_batch("fixtures/accuracy/sparse_002.txt", 64);
}
#[test]
fn accuracy_sparse_003() {
    accuracy_batch("fixtures/accuracy/sparse_003.txt", 64);
}
#[test]
fn accuracy_sparse_004() {
    accuracy_batch("fixtures/accuracy/sparse_004.txt", 64);
}
#[test]
fn accuracy_sparse_005() {
    accuracy_batch("fixtures/accuracy/sparse_005.txt", 64);
}
#[test]
fn accuracy_sparse_006() {
    accuracy_batch("fixtures/accuracy/sparse_006.txt", 64);
}
#[test]
fn accuracy_sparse_007() {
    accuracy_batch("fixtures/accuracy/sparse_007.txt", 64);
}
#[test]
fn accuracy_sparse_008() {
    accuracy_batch("fixtures/accuracy/sparse_008.txt", 64);
}
#[test]
fn accuracy_sparse_009() {
    accuracy_batch("fixtures/accuracy/sparse_009.txt", 64);
}
#[test]
fn accuracy_sparse_010() {
    accuracy_batch("fixtures/accuracy/sparse_010.txt", 64);
}
#[test]
fn accuracy_sparse_011() {
    accuracy_batch("fixtures/accuracy/sparse_011.txt", 64);
}
#[test]
fn accuracy_sparse_012() {
    accuracy_batch("fixtures/accuracy/sparse_012.txt", 64);
}
#[test]
fn accuracy_sparse_013() {
    accuracy_batch("fixtures/accuracy/sparse_013.txt", 64);
}
#[test]
fn accuracy_sparse_014() {
    accuracy_batch("fixtures/accuracy/sparse_014.txt", 64);
}
#[test]
fn accuracy_sparse_015() {
    accuracy_batch("fixtures/accuracy/sparse_015.txt", 64);
}
#[test]
fn accuracy_sparse_016() {
    accuracy_batch("fixtures/accuracy/sparse_016.txt", 64);
}
#[test]
fn accuracy_sparse_017() {
    accuracy_batch("fixtures/accuracy/sparse_017.txt", 64);
}
#[test]
fn accuracy_sparse_018() {
    accuracy_batch("fixtures/accuracy/sparse_018.txt", 64);
}
#[test]
fn accuracy_sparse_019() {
    accuracy_batch("fixtures/accuracy/sparse_019.txt", 64);
}
#[test]
fn accuracy_sparse_020() {
    accuracy_batch("fixtures/accuracy/sparse_020.txt", 64);
}
#[test]
fn accuracy_sparse_021() {
    accuracy_batch("fixtures/accuracy/sparse_021.txt", 64);
}
#[test]
fn accuracy_sparse_022() {
    accuracy_batch("fixtures/accuracy/sparse_022.txt", 64);
}
#[test]
fn accuracy_sparse_023() {
    accuracy_batch("fixtures/accuracy/sparse_023.txt", 64);
}
#[test]
fn accuracy_sparse_024() {
    accuracy_batch("fixtures/accuracy/sparse_024.txt", 64);
}
#[test]
fn accuracy_sparse_025() {
    accuracy_batch("fixtures/accuracy/sparse_025.txt", 64);
}
#[test]
fn accuracy_sparse_026() {
    accuracy_batch("fixtures/accuracy/sparse_026.txt", 64);
}
#[test]
fn accuracy_sparse_027() {
    accuracy_batch("fixtures/accuracy/sparse_027.txt", 64);
}
#[test]
fn accuracy_sparse_028() {
    accuracy_batch("fixtures/accuracy/sparse_028.txt", 64);
}
#[test]
fn accuracy_sparse_029() {
    accuracy_batch("fixtures/accuracy/sparse_029.txt", 64);
}
#[test]
fn accuracy_sparse_030() {
    accuracy_batch("fixtures/accuracy/sparse_030.txt", 64);
}
#[test]
fn accuracy_sparse_031() {
    accuracy_batch("fixtures/accuracy/sparse_031.txt", 64);
}
#[test]
fn accuracy_sparse_032() {
    accuracy_batch("fixtures/accuracy/sparse_032.txt", 64);
}
#[test]
fn accuracy_sparse_033() {
    accuracy_batch("fixtures/accuracy/sparse_033.txt", 64);
}
#[test]
fn accuracy_sparse_034() {
    accuracy_batch("fixtures/accuracy/sparse_034.txt", 64);
}
#[test]
fn accuracy_sparse_035() {
    accuracy_batch("fixtures/accuracy/sparse_035.txt", 64);
}
#[test]
fn accuracy_sparse_036() {
    accuracy_batch("fixtures/accuracy/sparse_036.txt", 64);
}
#[test]
fn accuracy_sparse_037() {
    accuracy_batch("fixtures/accuracy/sparse_037.txt", 64);
}
#[test]
fn accuracy_sparse_038() {
    accuracy_batch("fixtures/accuracy/sparse_038.txt", 64);
}
#[test]
fn accuracy_sparse_039() {
    accuracy_batch("fixtures/accuracy/sparse_039.txt", 64);
}
#[test]
fn accuracy_sparse_040() {
    accuracy_batch("fixtures/accuracy/sparse_040.txt", 64);
}
#[test]
fn accuracy_sparse_041() {
    accuracy_batch("fixtures/accuracy/sparse_041.txt", 64);
}
#[test]
fn accuracy_sparse_042() {
    accuracy_batch("fixtures/accuracy/sparse_042.txt", 64);
}
#[test]
fn accuracy_sparse_043() {
    accuracy_batch("fixtures/accuracy/sparse_043.txt", 64);
}
#[test]
fn accuracy_sparse_044() {
    accuracy_batch("fixtures/accuracy/sparse_044.txt", 64);
}
#[test]
fn accuracy_sparse_045() {
    accuracy_batch("fixtures/accuracy/sparse_045.txt", 64);
}
#[test]
fn accuracy_sparse_046() {
    accuracy_batch("fixtures/accuracy/sparse_046.txt", 22);
}
#[test]
fn accuracy_nested_000() {
    accuracy_batch("fixtures/accuracy/nested_000.txt", 2);
}
#[test]
fn accuracy_legacy_000() {
    accuracy_batch("fixtures/oracle/batch_00.txt", 64);
}
#[test]
fn accuracy_legacy_001() {
    accuracy_batch("fixtures/oracle/batch_01.txt", 64);
}
#[test]
fn accuracy_legacy_002() {
    accuracy_batch("fixtures/oracle/batch_02.txt", 64);
}
#[test]
fn accuracy_legacy_003() {
    accuracy_batch("fixtures/oracle/batch_03.txt", 64);
}
#[test]
fn accuracy_legacy_004() {
    accuracy_batch("fixtures/oracle/batch_04.txt", 64);
}
#[test]
fn accuracy_legacy_005() {
    accuracy_batch("fixtures/oracle/batch_05.txt", 46);
}
#[test]
fn accuracy_legacy_006() {
    accuracy_batch("fixtures/oracle/batch_06.txt", 2);
}
#[test]
fn accuracy_legacy_007() {
    accuracy_batch("fixtures/oracle/batch_07.txt", 1);
}
#[test]
fn accuracy_legacy_008() {
    accuracy_batch("fixtures/oracle/batch_08.txt", 1);
}
#[test]
fn accuracy_legacy_009() {
    accuracy_batch("fixtures/oracle/batch_09.txt", 1);
}
#[test]
fn accuracy_legacy_010() {
    accuracy_batch("fixtures/oracle/batch_10.txt", 1);
}
#[test]
fn accuracy_legacy_011() {
    accuracy_batch("fixtures/oracle/batch_11.txt", 1);
}
#[test]
fn accuracy_legacy_012() {
    accuracy_batch("fixtures/oracle/batch_12.txt", 64);
}
#[test]
fn accuracy_legacy_013() {
    accuracy_batch("fixtures/oracle/batch_13.txt", 46);
}
#[test]
fn accuracy_legacy_014() {
    accuracy_batch("fixtures/oracle/batch_14.txt", 2);
}
#[test]
fn accuracy_legacy_015() {
    accuracy_batch("fixtures/oracle/batch_15.txt", 1);
}
#[test]
fn accuracy_legacy_016() {
    accuracy_batch("fixtures/oracle/batch_16.txt", 1);
}
#[test]
fn accuracy_legacy_017() {
    accuracy_batch("fixtures/oracle/batch_17.txt", 1);
}
#[test]
fn accuracy_legacy_018() {
    accuracy_batch("fixtures/oracle/batch_18.txt", 1);
}
#[test]
fn accuracy_legacy_019() {
    accuracy_batch("fixtures/oracle/batch_19.txt", 1);
}
#[test]
fn accuracy_legacy_020() {
    accuracy_batch("fixtures/oracle/batch_20.txt", 64);
}
#[test]
fn accuracy_legacy_021() {
    accuracy_batch("fixtures/oracle/batch_21.txt", 46);
}
#[test]
fn accuracy_legacy_022() {
    accuracy_batch("fixtures/oracle/batch_22.txt", 2);
}
#[test]
fn accuracy_legacy_023() {
    accuracy_batch("fixtures/oracle/batch_23.txt", 1);
}
#[test]
fn accuracy_legacy_024() {
    accuracy_batch("fixtures/oracle/batch_24.txt", 1);
}
#[test]
fn accuracy_legacy_025() {
    accuracy_batch("fixtures/oracle/batch_25.txt", 1);
}
#[test]
fn accuracy_legacy_026() {
    accuracy_batch("fixtures/oracle/batch_26.txt", 1);
}
#[test]
fn accuracy_legacy_027() {
    accuracy_batch("fixtures/oracle/batch_27.txt", 1);
}
#[test]
fn accuracy_legacy_028() {
    accuracy_batch("fixtures/oracle/batch_28.txt", 64);
}
#[test]
fn accuracy_legacy_029() {
    accuracy_batch("fixtures/oracle/batch_29.txt", 46);
}
#[test]
fn accuracy_legacy_030() {
    accuracy_batch("fixtures/oracle/batch_30.txt", 2);
}
#[test]
fn accuracy_legacy_031() {
    accuracy_batch("fixtures/oracle/batch_31.txt", 1);
}
#[test]
fn accuracy_legacy_032() {
    accuracy_batch("fixtures/oracle/batch_32.txt", 1);
}
#[test]
fn accuracy_legacy_033() {
    accuracy_batch("fixtures/oracle/batch_33.txt", 1);
}
#[test]
fn accuracy_legacy_034() {
    accuracy_batch("fixtures/oracle/batch_34.txt", 1);
}
#[test]
fn accuracy_legacy_035() {
    accuracy_batch("fixtures/oracle/batch_35.txt", 1);
}
#[test]
fn accuracy_legacy_036() {
    accuracy_batch("fixtures/oracle/batch_36.txt", 64);
}
#[test]
fn accuracy_legacy_037() {
    accuracy_batch("fixtures/oracle/batch_37.txt", 46);
}
#[test]
fn accuracy_legacy_038() {
    accuracy_batch("fixtures/oracle/batch_38.txt", 2);
}
#[test]
fn accuracy_legacy_039() {
    accuracy_batch("fixtures/oracle/batch_39.txt", 1);
}
#[test]
fn accuracy_legacy_040() {
    accuracy_batch("fixtures/oracle/batch_40.txt", 1);
}
#[test]
fn accuracy_legacy_041() {
    accuracy_batch("fixtures/oracle/batch_41.txt", 1);
}
#[test]
fn accuracy_legacy_042() {
    accuracy_batch("fixtures/oracle/batch_42.txt", 1);
}
#[test]
fn accuracy_legacy_043() {
    accuracy_batch("fixtures/oracle/batch_43.txt", 1);
}
