// Generated by scripts/generate-fixtures.py; edit the generator.
use super::benchmark_support::oracle_batch;
#[test]
fn oracle_batch_00() {
    oracle_batch("fixtures/oracle/batch_00.txt", 64);
}
#[test]
fn oracle_batch_01() {
    oracle_batch("fixtures/oracle/batch_01.txt", 64);
}
#[test]
fn oracle_batch_02() {
    oracle_batch("fixtures/oracle/batch_02.txt", 64);
}
#[test]
fn oracle_batch_03() {
    oracle_batch("fixtures/oracle/batch_03.txt", 64);
}
#[test]
fn oracle_batch_04() {
    oracle_batch("fixtures/oracle/batch_04.txt", 64);
}
#[test]
fn oracle_batch_05() {
    oracle_batch("fixtures/oracle/batch_05.txt", 46);
}
#[test]
fn oracle_batch_06() {
    oracle_batch("fixtures/oracle/batch_06.txt", 2);
}
#[test]
fn oracle_batch_07() {
    oracle_batch("fixtures/oracle/batch_07.txt", 1);
}
#[test]
fn oracle_batch_08() {
    oracle_batch("fixtures/oracle/batch_08.txt", 1);
}
#[test]
fn oracle_batch_09() {
    oracle_batch("fixtures/oracle/batch_09.txt", 1);
}
#[test]
fn oracle_batch_10() {
    oracle_batch("fixtures/oracle/batch_10.txt", 1);
}
#[test]
fn oracle_batch_11() {
    oracle_batch("fixtures/oracle/batch_11.txt", 1);
}
#[test]
fn oracle_batch_12() {
    oracle_batch("fixtures/oracle/batch_12.txt", 64);
}
#[test]
fn oracle_batch_13() {
    oracle_batch("fixtures/oracle/batch_13.txt", 46);
}
#[test]
fn oracle_batch_14() {
    oracle_batch("fixtures/oracle/batch_14.txt", 2);
}
#[test]
fn oracle_batch_15() {
    oracle_batch("fixtures/oracle/batch_15.txt", 1);
}
#[test]
fn oracle_batch_16() {
    oracle_batch("fixtures/oracle/batch_16.txt", 1);
}
#[test]
fn oracle_batch_17() {
    oracle_batch("fixtures/oracle/batch_17.txt", 1);
}
#[test]
fn oracle_batch_18() {
    oracle_batch("fixtures/oracle/batch_18.txt", 1);
}
#[test]
fn oracle_batch_19() {
    oracle_batch("fixtures/oracle/batch_19.txt", 1);
}
#[test]
fn oracle_batch_20() {
    oracle_batch("fixtures/oracle/batch_20.txt", 64);
}
#[test]
fn oracle_batch_21() {
    oracle_batch("fixtures/oracle/batch_21.txt", 46);
}
#[test]
fn oracle_batch_22() {
    oracle_batch("fixtures/oracle/batch_22.txt", 2);
}
#[test]
fn oracle_batch_23() {
    oracle_batch("fixtures/oracle/batch_23.txt", 1);
}
#[test]
fn oracle_batch_24() {
    oracle_batch("fixtures/oracle/batch_24.txt", 1);
}
#[test]
fn oracle_batch_25() {
    oracle_batch("fixtures/oracle/batch_25.txt", 1);
}
#[test]
fn oracle_batch_26() {
    oracle_batch("fixtures/oracle/batch_26.txt", 1);
}
#[test]
fn oracle_batch_27() {
    oracle_batch("fixtures/oracle/batch_27.txt", 1);
}
#[test]
fn oracle_batch_28() {
    oracle_batch("fixtures/oracle/batch_28.txt", 64);
}
#[test]
fn oracle_batch_29() {
    oracle_batch("fixtures/oracle/batch_29.txt", 46);
}
#[test]
fn oracle_batch_30() {
    oracle_batch("fixtures/oracle/batch_30.txt", 2);
}
#[test]
fn oracle_batch_31() {
    oracle_batch("fixtures/oracle/batch_31.txt", 1);
}
#[test]
fn oracle_batch_32() {
    oracle_batch("fixtures/oracle/batch_32.txt", 1);
}
#[test]
fn oracle_batch_33() {
    oracle_batch("fixtures/oracle/batch_33.txt", 1);
}
#[test]
fn oracle_batch_34() {
    oracle_batch("fixtures/oracle/batch_34.txt", 1);
}
#[test]
fn oracle_batch_35() {
    oracle_batch("fixtures/oracle/batch_35.txt", 1);
}
#[test]
fn oracle_batch_36() {
    oracle_batch("fixtures/oracle/batch_36.txt", 64);
}
#[test]
fn oracle_batch_37() {
    oracle_batch("fixtures/oracle/batch_37.txt", 46);
}
#[test]
fn oracle_batch_38() {
    oracle_batch("fixtures/oracle/batch_38.txt", 2);
}
#[test]
fn oracle_batch_39() {
    oracle_batch("fixtures/oracle/batch_39.txt", 1);
}
#[test]
fn oracle_batch_40() {
    oracle_batch("fixtures/oracle/batch_40.txt", 1);
}
#[test]
fn oracle_batch_41() {
    oracle_batch("fixtures/oracle/batch_41.txt", 1);
}
#[test]
fn oracle_batch_42() {
    oracle_batch("fixtures/oracle/batch_42.txt", 1);
}
#[test]
fn oracle_batch_43() {
    oracle_batch("fixtures/oracle/batch_43.txt", 1);
}
