[package]
name = "game_components_presets"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
game_components_metagame = { path = "../metagame" }
game_components_economy = { path = "../economy" }
game_components_interfaces = { path = "../interfaces" }
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_access.workspace = true
ekubo.workspace = true

[[target.starknet-contract]]

[dev-dependencies]
snforge_std.workspace = true
game_components_testing = { path = "../testing" }
game_components_test_common = { path = "../test_common" }
openzeppelin_interfaces.workspace = true
