[package]
name = "game_components_presets"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
game_components_leaderboard = { path = "../leaderboard" }
game_components_tokenomics = { path = "../tokenomics" }
game_components_interfaces = { path = "../interfaces" }
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_access.workspace = true
ekubo.workspace = true

[[target.starknet-contract]]

[dev-dependencies]
snforge_std.workspace = true