[package]
name = "game_components_embeddable_game_standard"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_access.workspace = true
# Game components dependencies
game_components_interfaces = { path = "../interfaces" }
game_components_utilities = { path = "../utilities" }

[dev-dependencies]
snforge_std.workspace = true
game_components_testing = { path = "../testing" }
game_components_test_common = { path = "../test_common" }
openzeppelin_token.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "game_components_test_common::mocks::game_metadata_mock::GameMetadataMock",
    "game_components_test_common::mocks::metagame_mock::metagame_mock",
    "game_components_test_common::mocks::mock_game::MockGame",
    "game_components_test_common::mocks::standard_game_mock::StandardGameMock",
]
