[package]
name = "game_components_registry"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]
starknet.workspace = true
game_components_interfaces = { path = "../interfaces" }
game_components_minigame = { path = "../minigame" }
openzeppelin_interfaces.workspace = true
openzeppelin_introspection.workspace = true

[[target.starknet-contract]]

[dev-dependencies]
snforge_std.workspace = true
openzeppelin_token.workspace = true
game_components_testing = { path = "../testing" }
game_components_test_common = { path = "../test_common" }
