[package]
name = "game_components_registry"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
game_components_minigame = { path = "../minigame" }
openzeppelin_interfaces.workspace = true
openzeppelin_introspection.workspace = true

[lib]
