[package]
name = "game_components_prize"
version.workspace = true
edition.workspace = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_introspection.workspace = true
game_components_interfaces = { path = "../interfaces" }
game_components_distribution = { path = "../distribution" }

[dev-dependencies]
snforge_std.workspace = true
